### ISSUE TITLE
Reload leads to exception for ASR920 console connection

### ISSUE THREAD

**Issue by jamesjwei** [kstaniek/condoor#16]
he exception in condoor.log:
 
2017-03-26 02:56:37,970 [   DEBUG] condoor.fsm:run(152): IOS-RELOAD Start
2017-03-26 02:56:38,806 [   DEBUG] condoor.fsm:run(176): E=1,S=0,T=10,RT=0.84
2017-03-26 02:56:38,807 [   DEBUG] condoor.fsm:call_action(23): A=Send text line to the controller.
2017-03-26 02:56:39,107 [   DEBUG] condoor.fsm:run(193): NS=2,NT=10
2017-03-26 02:56:49,118 [   DEBUG] condoor.fsm:run(176): E=2,S=2,T=10,RT=10.01
2017-03-26 02:56:49,119 [   DEBUG] condoor.fsm:call_action(23): A=Disconnect from the device when device is reloading.
2017-03-26 02:56:49,119 [   DEBUG] condoor.controller:disconnect(92): Disconnecting the sessions
2017-03-26 02:56:49,220 [   DEBUG] condoor.controller:disconnect(95): Disconnected
2017-03-26 02:56:49,220 [   DEBUG] condoor.fsm:run(193): NS=-1,NT=10
2017-03-26 02:56:49,221 [   DEBUG] condoor.fsm:run(203): IOS-RELOAD Stop at E=2,S=-1
2017-03-26 02:56:49,221 [   DEBUG] condoor.device:disconnect(187): Disconnecting: telnet://@10.64.97.222:2003
2017-03-26 02:56:49,221 [   DEBUG] condoor.device:send(221): Sending command: 'exit'
2017-03-26 02:56:49,522 [CRITICAL] condoor.device:execute_command(281): Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/condoor-1.0.0b3-py2.7.egg/condoor/device.py", line 244, in execute_command
    self.ctrl.send_command(cmd, password=password)
  File "/usr/local/lib/python2.7/dist-packages/condoor-1.0.0b3-py2.7.egg/condoor/controller.py", line 85, in send_command
    self.send(cmd)  # pylint: disable=no-member
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 526, in send
    return os.write(self.child_fd, b)
OSError: [Errno 9] Bad file descriptor
2017-03-26 02:56:49,544 [   ERROR] condoor.device:send(226): Connection lost. Disconnecting.

**Comment by kstaniek** [comment]
@jamesjwei Will be fixed in next beta. Thanks.

**Comment by kstaniek** [comment]
I will handle the OSError but raise ConnectionError("Session already disconnected"). User must handle this situation if this is unexpected. It may happen when sending 'exit' type of command when device started reload sequence and disconnected the session first. In other cases this may indicate the connection error.
