### ISSUE TITLE
Exception: TypeError: got <type 'NoneType'> (None) as pattern, must be one of: <type 'basestring'>, pexpect.EOF, pexpect.TIMEOUT

### ISSUE THREAD

**Issue by kstaniek** [kstaniek/condoor#20]
```
2017-03-31 22:59:33,279 [CRITICAL] condoor.device:execute_command(281): Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/device.py", line 248, in execute_command
    if not self.driver.wait_for_string(wait_for_string, timeout):
  File "/usr/local/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/drivers/generic.py", line 219, in wait_for_string
    return fsm.run()
  File "/usr/local/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/fsm.py", line 158, in run
    ctx.event = self.ctrl.expect(self.events, searchwindowsize=self.searchwindowsize, timeout=timeout)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/site-packages/pexpect/spawnbase.py", line 319, in expect
    compiled_pattern_list = self.compile_pattern_list(pattern)
  File "/usr/local/lib/python2.7/site-packages/pexpect/spawnbase.py", line 221, in compile_pattern_list
    self._pattern_type_err(p)
  File "/usr/local/lib/python2.7/site-packages/pexpect/spawnbase.py", line 172, in _pattern_type_err
    for ast in self.allowed_string_types])
TypeError: got <type 'NoneType'> (None) as pattern, must be one of: <type 'basestring'>, pexpect.EOF, pexpect.TIMEOUT
2017-03-31 22:59:33,281 [   ERROR] condoor.device:send(226): Connection lost. Disconnecting.
```

**Comment by kstaniek** [comment]
Caused by clearing the jumphost cache information before reload when connected over console.
