### ISSUE TITLE
eXR console connection failed after router reload

### ISSUE THREAD

**Issue by jamesjwei** [kstaniek/condoor#22]
Install activate the following three packages. There was exception after reload.

asr9k-k9sec-x64-2.2.0.0-r613.x86_64.rpm
asr9k-m2m-x64-2.0.0.0-r613.x86_64.rpm
asr9k-mini-x64-6.1.3.iso

System log:

Traceback (most recent call last):
File "/Users/jawei/Documents/new/csm-master/csmserver/handlers/base.py", line 64, in execute
self.start(ctx)
File "/Users/jawei/Documents/new/csm-master/csmserver/handlers/base.py", line 209, in start
pm.dispatch("run")
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/csm_pm.py", line 154, in dispatch
results += self._manager.map_method(self._dispatch, func)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/dispatch.py", line 111, in map_method
method_name, *args, **kwds)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/dispatch.py", line 86, in map
self._invoke_one_plugin(response.append, func, e, args, kwds)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/extension.py", line 275, in _invoke_one_plugin
response_callback(func(e, *args, **kwds))
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/extension.py", line 249, in _call_extension_method
return getattr(extension.obj, method_name)(*args, **kwds)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/core_plugins/csm_install_operations/exr/activate.py", line 125, in run
install_activate_deactivate(self.ctx, cmd)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/core_plugins/csm_install_operations/exr/install.py", line 501, in install_activate_deactivate
if not ctx.run_fsm("ACTIVATE-OR-DEACTIVATE", cmd, events, transitions, timeout=300):
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/decorators.py", line 51, in
return lambda self, *args, **kwargs: getter(attribute, name, self)(*args, **kwargs)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/connection.py", line 453, in run_fsm
return self._chain.target_device.run_fsm(name, command, events, transitions, timeout, max_transitions)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/device.py", line 456, in run_fsm
return FSM(name, self, events, transitions, timeout=timeout, max_transitions=max_transitions).run()
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/fsm.py", line 178, in run
if not action_instance(ctx):
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/core_plugins/csm_install_operations/exr/install.py", line 369, in handle_reload_activate_deactivate
success = wait_for_reload(plugin_ctx)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/core_plugins/csm_install_operations/exr/install.py", line 208, in wait_for_reload
ctx.reload(reload_timeout=1500, no_reload_cmd=True)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/decorators.py", line 51, in
return lambda self, *args, **kwargs: getter(attribute, name, self)(*args, **kwargs)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/connection.py", line 377, in reload
self._chain.target_device.reload(reload_timeout, save_config, no_reload_cmd)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/device.py", line 451, in reload
self.driver.reload(reload_timeout, save_config)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/drivers/eXR.py", line 168, in reload
return fsm.run()
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/fsm.py", line 158, in run
ctx.event = self.ctrl.expect(self.events, searchwindowsize=self.searchwindowsize, timeout=timeout)
File "", line 1, in
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/spawnbase.py", line 321, in expect
timeout, searchwindowsize, async)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/spawnbase.py", line 345, in expect_list
return exp.expect_loop(timeout)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/expect.py", line 107, in expect_loop
return self.timeout(e)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/expect.py", line 70, in timeout
raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
 
command: /usr/bin/telnet
args: ['/usr/bin/telnet', '172.27.148.159', '2037']
buffer (last 100 chars): 'tpd.\r\r\nStarting crond: OK\r\r\nCreating default host password file\r\ninitctl: Unknown instance: /dev/\r\r\n'
before (last 100 chars): 'tpd.\r\r\nStarting crond: OK\r\r\nCreating default host password file\r\ninitctl: Unknown instance: /dev/\r\r\n'
after:
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 45310
child_fd: 15
closed: False
timeout: 30
delimiter:
logfile: None
logfile_read:
logfile_send: None
maxread: 65536
ignorecase: False
searchwindowsize: 4000
delaybeforesend: 0.3
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
0: re.compile("admin hw-module location all reload")
1: re.compile("Reload\ hardware\ module\ \?\ \[no\,yes\]")
2: re.compile("Status report.*START TO BACKUP")
3: re.compile("Status report.*BACKUP HAS COMPLETED SUCCESSFULLY")
4: re.compile("\[Done\]")
5: re.compile("Booting IOS-XR 64 bit Boot previously installed image")
6: re.compile("ios con[0|1]/(?:RS?P)?[0-1]/CPU0 is now available")
7: re.compile("Press RETURN to get started\.")
8: re.compile("SYSTEM CONFIGURATION COMPLETED")
9: re.compile("SYSTEM CONFIGURATION IN PROCESS")
10: EOF

**Comment by kstaniek** [comment]
This looks like the state machine does not handle the reload properly. Can I get the session.log please?

**Comment by kstaniek** [comment]
The pexpect.TIMEOUT was not added to the FSM for reload. 
I think that reload took more than 10min and the exception was raised.
I extended the timeout for next state after detecting "Booting IOS-XR 64 bit Boot previously installed image - Press Ctrl-c to stop” on the console from 10min to 30min
Also added the TIMEOUT state handling to see more details next time it happens.

The change is pushed to develop, however the issue stays open till getting the confirmation the fix works.

See 18f4cfe for details.
