### ISSUE TITLE
IOS-XE exception after router reload

### ISSUE THREAD

**Issue by jamesjwei** [kstaniek/condoor#23]
Reload ASR907 which is connected via console. There is an exception after router reload.

System Log:

Traceback (most recent call last):
File "/Users/jawei/Documents/new/csm-master/csmserver/handlers/base.py", line 64, in execute
self.start(ctx)
File "/Users/jawei/Documents/new/csm-master/csmserver/handlers/base.py", line 213, in start
raise e
CommandTimeoutError: ASR907-1: Command timeout: 'exit'

**Comment by kstaniek** [comment]
Can you provide full condoor.log and session.log?

**Comment by kstaniek** [comment]
Modified disconnect method: b5fb05d
Please verify.
