### ISSUE TITLE
NCS6K: Timeout waiting to connect after reload

### ISSUE THREAD

**Issue by anushreejangid** [kstaniek/condoor#27]
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpe/csmpe/__main__.py", line 375, in <module>
    cli()
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpe/csmpe/__main__.py", line 360, in jsonparser
    results = pm.dispatch("run")
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpe/csmpe/csm_pm.py", line 154, in dispatch
    results += self._manager.map_method(self._dispatch, func)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/stevedore-1.21.0-py2.7.egg/stevedore/dispatch.py", line 111, in map_method
    method_name, *args, **kwds)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/stevedore-1.21.0-py2.7.egg/stevedore/dispatch.py", line 86, in map
    self._invoke_one_plugin(response.append, func, e, args, kwds)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/stevedore-1.21.0-py2.7.egg/stevedore/extension.py", line 286, in _invoke_one_plugin
    response_callback(func(e, *args, **kwds))
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/stevedore-1.21.0-py2.7.egg/stevedore/extension.py", line 260, in _call_extension_method
    return getattr(extension.obj, method_name)(*args, **kwds)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpe/csmpe/core_plugins/csm_install_operations/exr/activate.py", line 137, in run
    install_activate_deactivate(self.ctx, cmd)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpe/csmpe/core_plugins/csm_install_operations/exr/install.py", line 565, in install_activate_deactivate
    if not ctx.run_fsm("ACTIVATE-OR-DEACTIVATE", cmd, events, transitions, timeout=300):
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpe/csmpe/decorators.py", line 51, in <lambda>
    return lambda self, *args, **kwargs: getter(attribute, name, self)(*args, **kwargs)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/condoor-1.0.0b3-py2.7.egg/condoor/connection.py", line 450, in run_fsm
    return self._chain.target_device.run_fsm(name, command, events, transitions, timeout, max_transitions)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/condoor-1.0.0b3-py2.7.egg/condoor/device.py", line 456, in run_fsm
    return FSM(name, self, events, transitions, timeout=timeout, max_transitions=max_transitions).run()
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/condoor-1.0.0b3-py2.7.egg/condoor/fsm.py", line 178, in run
    if not action_instance(ctx):
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpe/csmpe/core_plugins/csm_install_operations/exr/install.py", line 432, in handle_issu_reload
    success = wait_for_reload(plugin_ctx)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpe/csmpe/core_plugins/csm_install_operations/exr/install.py", line 210, in wait_for_reload
    ctx.reload(reload_timeout=1500, no_reload_cmd=True)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpe/csmpe/decorators.py", line 51, in <lambda>
    return lambda self, *args, **kwargs: getter(attribute, name, self)(*args, **kwargs)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/condoor-1.0.0b3-py2.7.egg/condoor/connection.py", line 374, in reload
    self._chain.target_device.reload(reload_timeout, save_config, no_reload_cmd)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/condoor-1.0.0b3-py2.7.egg/condoor/device.py", line 451, in reload
    self.driver.reload(reload_timeout, save_config)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/condoor-1.0.0b3-py2.7.egg/condoor/drivers/eXR.py", line 168, in reload
    return fsm.run()
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/condoor-1.0.0b3-py2.7.egg/condoor/fsm.py", line 158, in run
    ctx.event = self.ctrl.expect(self.events, searchwindowsize=self.searchwindowsize, timeout=timeout)
  File "<string>", line 1, in <lambda>
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/pexpect-4.2.1-py2.7.egg/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/pexpect-4.2.1-py2.7.egg/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/pexpect-4.2.1-py2.7.egg/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/Users/anjangid/Desktop/csmpe_mainbranch/csmpeenv/lib/python2.7/site-packages/pexpect-4.2.1-py2.7.egg/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x10225fe50>
command: /usr/bin/telnet
args: ['/usr/bin/telnet', '10.105.236.18', '2015']
buffer (last 100 chars): 'n_count: No such file or directory\r\r\n\r\r\n\r\r\r\n\rios con0/RP1/CPU0 is in standby\r\r\n\r\r\r\n\r\r\r\n\r\r\r\n\r\r\r\n\r\r\r\n\r'
before (last 100 chars): 'n_count: No such file or directory\r\r\n\r\r\n\r\r\r\n\rios con0/RP1/CPU0 is in standby\r\r\n\r\r\r\n\r\r\r\n\r\r\r\n\r\r\r\n\r\r\r\n\r'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 7094
child_fd: 13
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: <condoor.utils.FilteredFile object at 0x10225fb50>
logfile_send: None
maxread: 65536
ignorecase: False
searchwindowsize: 4000
delaybeforesend: 0.3
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("admin hw-module location all reload")
    1: re.compile("Reload\ hardware\ module\ \?\ \[no\,yes\]")
    2: re.compile("Status report.*START TO BACKUP")
    3: re.compile("Status report.*BACKUP HAS COMPLETED SUCCESSFULLY")
    4: re.compile("\[Done\]")
    5: re.compile("Booting IOS-XR 64 bit Boot previously installed image")
    6: re.compile("ios con[0|1]/(?:RS?P)?[0-1]/CPU0 is now available")
    7: re.compile("Press RETURN to get started\.")
    8: re.compile("SYSTEM CONFIGURATION COMPLETED")
    9: re.compile("SYSTEM CONFIGURATION IN PROCESS")
    10: EOF

[session.txt](https://github.com/kstaniek/condoor/files/912000/session.txt)
[condoor.txt](https://github.com/kstaniek/condoor/files/912001/condoor.txt)

**Comment by kstaniek** [comment]
reload method in eXR driver fixed.
