### ISSUE TITLE
ASR902 after reload '‘Calculating SHA-1 hash...’' is taken as the prompt

### ISSUE THREAD

**Issue by jamesjwei** [kstaniek/condoor#29]
This is single RSP host with console connection.

condoor seems to have taken ‘Calculating SHA-1 hash...’ as the new prompt after reload.

2017-04-12 13:23:51,352 [   DEBUG] condoor.controller:detect_prompt(174): Detected prompt: 'Calculating SHA-1 hash...'

2017-04-12 13:24:21,663 [    INFO] condoor.connection:emit_message(463): Time elapsed 573s/3600s

The full log is sent in email. Below is the system log:
Traceback (most recent call last):
File "/Users/jawei/Documents/new/csm-master/csmserver/handlers/base.py", line 64, in execute
self.start(ctx)
File "/Users/jawei/Documents/new/csm-master/csmserver/handlers/base.py", line 209, in start
pm.dispatch("run")
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/csm_pm.py", line 154, in dispatch
results += self._manager.map_method(self._dispatch, func)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/dispatch.py", line 111, in map_method
method_name, *args, **kwds)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/dispatch.py", line 86, in map
self._invoke_one_plugin(response.append, func, e, args, kwds)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/extension.py", line 275, in _invoke_one_plugin
response_callback(func(e, *args, **kwds))
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/extension.py", line 249, in _call_extension_method
return getattr(extension.obj, method_name)(*args, **kwds)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/core_plugins/csm_install_operations/ios_xe/activate.py", line 119, in run
install_activate_reload(self.ctx)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/core_plugins/csm_install_operations/ios_xe/install.py", line 224, in install_activate_reload
success = wait_for_reload(ctx)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/core_plugins/csm_install_operations/ios_xe/install.py", line 72, in wait_for_reload
ctx.reconnect(max_timeout=3600, force_discovery=True) # 60 * 60 = 3600
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/decorators.py", line 51, in
return lambda self, *args, **kwargs: getter(attribute, name, self)(*args, **kwargs)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/connection.py", line 299, in reconnect
prompt = chain.ctrl.detect_prompt()
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/controller.py", line 177, in detect_prompt
self.expect(compiled_prompt) # pylint: disable=no-member
File "", line 1, in
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/spawnbase.py", line 321, in expect
timeout, searchwindowsize, async)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/spawnbase.py", line 345, in expect_list
return exp.expect_loop(timeout)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/expect.py", line 107, in expect_loop
return self.timeout(e)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/expect.py", line 70, in timeout
raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
 
command: /usr/bin/telnet
args: ['/usr/bin/telnet', '10.64.97.171', '2057']
buffer (last 100 chars): '10eb760f:aa93f8eb:d00b187b:9291d018:a5da7147\n\rImage validated\n\rPassing control to the main image..\n\r'
before (last 100 chars): '10eb760f:aa93f8eb:d00b187b:9291d018:a5da7147\n\rImage validated\n\rPassing control to the main image..\n\r'
after:
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 57103
child_fd: 15
closed: False
timeout: 30
delimiter:
logfile: None
logfile_read:
logfile_send: None
maxread: 65536
ignorecase: False
searchwindowsize: 4000
delaybeforesend: 0.3
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
0: re.compile("(
|
)Calculating\ SHA\-1\ hash\.\.\.")

**Comment by kstaniek** [comment]
Full logs are needed.
