### ISSUE TITLE
I/O error related to searchwindowsize

### ISSUE THREAD

**Issue by jamesjwei** [kstaniek/condoor#3]
ERROR: InventoryManager hit exception - hostname = PAN-5201-ASR903, inventory job = 27 - 2017-02-03 00:02:16
Traceback (most recent call last):
File "/home/administrator/xe/csm-master/csmserver/work_units/inventory_work_unit.py", line 68, in start
handler_class = get_inventory_handler_class(ctx)
File "/home/administrator/xe/csm-master/csmserver/handlers/loader.py", line 57, in get_inventory_handler_class
discover_platform_info(ctx)
File "/home/administrator/xe/csm-master/csmserver/handlers/loader.py", line 38, in discover_platform_info
conn.connect(force_discovery=True)
File "/usr/local/lib/python2.7/dist-packages/condoor-1.0.0a4-py2.7.egg/condoor/connection.py", line 208, in connect
if chain.connect():
File "/usr/local/lib/python2.7/dist-packages/condoor-1.0.0a4-py2.7.egg/condoor/chain.py", line 52, in connect
if device.connect(self.ctrl):
File "/usr/local/lib/python2.7/dist-packages/condoor-1.0.0a4-py2.7.egg/condoor/device.py", line 117, in connect
if self.protocol.connect(self.driver):
File "/usr/local/lib/python2.7/dist-packages/condoor-1.0.0a4-py2.7.egg/condoor/protocols/telnet.py", line 72, in connect
return fsm.run()
File "/usr/local/lib/python2.7/dist-packages/condoor-1.0.0a4-py2.7.egg/condoor/fsm.py", line 158, in run
ctx.event = self.ctrl.expect(self.events, searchwindowsize=self.searchwindowsize, timeout=timeout)
File "", line 1, in
File "/usr/local/lib/python2.7/dist-packages/pexpect-4.2.1-py2.7.egg/pexpect/spawnbase.py", line 321, in expect
timeout, searchwindowsize, async)
File "/usr/local/lib/python2.7/dist-packages/pexpect-4.2.1-py2.7.egg/pexpect/spawnbase.py", line 345, in expect_list
return exp.expect_loop(timeout)
File "/usr/local/lib/python2.7/dist-packages/pexpect-4.2.1-py2.7.egg/pexpect/expect.py", line 99, in expect_loop
incoming = spawn.read_nonblocking(spawn.maxread, timeout)
File "/usr/local/lib/python2.7/dist-packages/pexpect-4.2.1-py2.7.egg/pexpect/pty_spawn.py", line 465, in read_nonblocking
return super(spawn, self).read_nonblocking(size)
File "/usr/local/lib/python2.7/dist-packages/pexpect-4.2.1-py2.7.egg/pexpect/spawnbase.py", line 163, in read_nonblocking
self._log(s, 'read')
File "/usr/local/lib/python2.7/dist-packages/pexpect-4.2.1-py2.7.egg/pexpect/spawnbase.py", line 125, in _log
second_log.write(s)
IOError: [Errno 5] Input/output error

**Comment by kstaniek** [comment]
Googled a bit and it seems to be a more complex problem. Rather not related to searchwindowsize.

**Comment by kstaniek** [comment]
Can recreate.
