### ISSUE TITLE
ASR901 write memory pexpect timeout

### ISSUE THREAD

**Issue by jamesjwei** [kstaniek/condoor#31]
pexpect timeout occurs with write memory:
CSG-5702-ASR901#write memory
Warning: Attempting to overwrite an NVRAM configuration previously written
by a different version of the system image.
Overwrite the previous NVRAM configuration?[confirm]

The error log is given below and the full log is sent via email.

Traceback (most recent call last):
File "/Users/jawei/Documents/new/csm-master/csmserver/handlers/base.py", line 64, in execute
self.start(ctx)
File "/Users/jawei/Documents/new/csm-master/csmserver/handlers/base.py", line 209, in start
pm.dispatch("run")
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/csm_pm.py", line 154, in dispatch
results += self._manager.map_method(self._dispatch, func)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/dispatch.py", line 111, in map_method
method_name, *args, **kwds)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/dispatch.py", line 86, in map
self._invoke_one_plugin(response.append, func, e, args, kwds)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/extension.py", line 275, in _invoke_one_plugin
response_callback(func(e, *args, **kwds))
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/stevedore/extension.py", line 249, in _call_extension_method
return getattr(extension.obj, method_name)(*args, **kwds)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/core_plugins/csm_install_operations/ios/activate.py", line 82, in run
install_activate_write_memory(self.ctx, cmd, self.ctx._connection.hostname)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/core_plugins/csm_install_operations/ios/install.py", line 166, in install_activate_write_memory
if not ctx.run_fsm("write memory", cmd, events, transitions, timeout=1200):
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/csmpe-0.1.5-py2.7.egg/csmpe/decorators.py", line 51, in 
return lambda self, *args, **kwargs: getter(attribute, name, self)(*args, **kwargs)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/connection.py", line 467, in run_fsm
return self._chain.target_device.run_fsm(name, command, events, transitions, timeout, max_transitions)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/device.py", line 473, in run_fsm
return FSM(name, self, events, transitions, timeout=timeout, max_transitions=max_transitions).run()
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/condoor-1.0.0b4-py2.7.egg/condoor/fsm.py", line 158, in run
ctx.event = self.ctrl.expect(self.events, searchwindowsize=self.searchwindowsize, timeout=timeout)
File "", line 1, in 
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/spawnbase.py", line 321, in expect
timeout, searchwindowsize, async)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/spawnbase.py", line 345, in expect_list
return exp.expect_loop(timeout)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/expect.py", line 107, in expect_loop
return self.timeout(e)
File "/Users/jawei/Documents/new/env/lib/python2.7/site-packages/pexpect/expect.py", line 70, in timeout
raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.

command: /usr/bin/telnet
args: ['/usr/bin/telnet', '172.20.163.167', '2047']
buffer (last 100 chars): 'NFIG_I: Configured from console by console'
before (last 100 chars): 'NFIG_I: Configured from console by console'
after: 
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 22546
child_fd: 15
closed: False
timeout: 30
delimiter: 
logfile: None
logfile_read: 
logfile_send: None
maxread: 65536
ignorecase: False
searchwindowsize: 4000
delaybeforesend: 0.3
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
0: re.compile("CSG-5702-ASR901")
1: re.compile("Overwrite the previous NVRAM configuration?[confirm]")
2: re.compile("[OK]")

**Comment by kstaniek** [comment]
```
Build_config = re.compile("[OK]")
Overwrite_warning = re.compile("Overwrite the previous NVRAM configuration?[confirm]")

```
should be escaped:

```
Build_config = re.compile(re.escape("[OK]"))
Overwrite_warning = re.compile(re.escape("Overwrite the previous NVRAM configuration?[confirm]"))

```

**Comment by kstaniek** [comment]
This seems to be a csmpe plugin issue.
